"""Add account lockout fields

Revision ID: e442962f40bf
Revises: 20251106_0001
Create Date: 2025-11-06 12:31:04.049139+07:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e442962f40bf"
down_revision: Union[str, None] = "20251106_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add account lockout fields
    op.add_column("users", sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("users", sa.Column("last_failed_login", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("locked_until", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove account lockout fields
    op.drop_column("users", "locked_until")
    op.drop_column("users", "last_failed_login")
    op.drop_column("users", "failed_login_attempts")
    # ### end Alembic commands ###
